export const TABLES = {
    schemaMigrations: 'schema_migrations',
    branches: 'branches',
    users: 'users',
    roles: 'roles',
    permissions: 'permissions',
    rolePermissions: 'role_permissions',
    accounts: 'accounts',
    journalEntries: 'journal_entries',
    journalLines: 'journal_lines',
    categories: 'categories',
    units: 'units',
    unitConversions: 'unit_conversions',
    products: 'products',
    recipes: 'recipes',
    inventoryMovements: 'inventory_movements',
    inventoryStock: 'inventory_stock',
    customers: 'customers',
    posSessions: 'pos_sessions',
    orders: 'orders',
    orderLines: 'order_lines',
    orderNotes: 'order_notes',
    payments: 'payments',
    cashMovements: 'cash_movements',
    printers: 'printers',
    printerRoutes: 'printer_routes',
    printJobs: 'print_jobs',
    printTemplates: 'print_templates',
    workstations: 'workstations',
    settings: 'settings',
    settingsHistory: 'settings_history',
    auditLogs: 'audit_logs',
    fiscalPeriods: 'fiscal_periods',
    sequences: 'sequences',
    suppliers: 'suppliers',
    purchaseInvoices: 'purchase_invoices',
    purchaseInvoiceLines: 'purchase_invoice_lines',
    salesInvoices: 'sales_invoices',
    salesInvoiceLines: 'sales_invoice_lines',
    managerApprovals: 'manager_approvals'
} as const;

export type TableName = (typeof TABLES)[keyof typeof TABLES];
